language: java
jdk:
- oraclejdk8
script: mvn clean package
deploy:
  - provider: releases
    api_key:
      secure: o4KJtC2DTodDChIO/gQNVK0uSj8M46o9Mxd/99jEs8K9eiHK20VZJDuCJVLXNyXXuhb3Jdn0coS2jX1Dk1sHQv9S2OSZpXanMHipqdEO9OGD/Zqt3dmuCBP+iYw9I3oqTp9cXcaZ/upc5ePnqS7BH/YpBDEHBL3lzwq/Y8iYB403lXGXCYLCX7e6q5EMaMNDYttrhClqwgRFEa5ENuyyjbN3yudk9jeThOAgS5lqcdNs4h4guc2tR1bxOWFyBzfE/vGucYEHAtSnkPUK+tYNS6wSE6L2fT51XX5Hhlq9kjCea9fsOxxVSoIRrqOPCnvoSH4R++VQUtpDjP1Gdra3luOlNXg4B2/uQH3g+2LuXj35sKrbkd1bxKBqyFssK30OfUa0uCkxkCC+a/UyBuN8FLaqCqMavxw/ieB848yMWSfQb8ihDLEV1aMLoiD8uKMWiViCfMwbWSUoog4+vw9nHVZrtQHIXiCzEKLVavW9MmCGTc932ROQvfJAFwwbuJZB9ffXbB6cjTAo1iI528IoIVJ2HoyBUh6cOE8/0F4VvKOmb0ZOHP2BcvAZ0xEuQLHDpr3XIcr4V/si6MrxsUYejCusefCYMgTMppOAWKnTz8lbdyJvRnlPw9US6EHItPbfWPR5AY7SZlhb9h+BsHLhdOHPDR4FuqYkwJeSY8qFZfc=
    file_glob: true
    skip_cleanup: true
    file:
      - nifi-sqllookup-services-api-nar/target/*.nar
      - nifi-sqllookup-services-nar/target/*.nar
    on:
      repo: mrcsparker/nifi-sqllookup-services-bundle
      tags: true
  - provider: bintray
    file: descriptor.json
    user: mrcsparker
    skip_cleanup: true
    on:
      repo: mrcsparker/nifi-sqllookup-services-bundle
      tags: true
    key:
      secure: gkkrOHFmcCQ+38F5nu6cSfgH+ioRIx/+eromgfhiahnqooeFMPqg19eGT9iJLYrrMzAZBg5j+9spNAL9nEv+C9IZTPH7KQECJbxdHyzt4iewyjblxdLGNY7nPSOKHbZIQp6PSek2Kbn0P7MrhzsVafxBIQQeBNQynP8AixtTnqVsrXonfBzuyIOXf9Y8tpBsjX5Jgxste0PlI4Ymkv8oLXW4+XSbeIhTM4wIuw3w3fDATgFnzWKsukDaco154Yf7MEPQLXf81dTn3KjQ4rgtChluIg9R4QMhwreHgdMku0Yxa7aH+UAq0wm8x6J0SchIzJIaSVld20PyJ9JAeHregVF4HtSoxuyQgY3OOsd6eEg540tZIFrQ8Ad3fSgRzy882yjYUS9G3aT7HokFUBLVZznxqYWxRWRvFAx0c3waeNZRapLM0dpngQeeKZjw6OXPjamjiPDHC7eMXz8X7TPHs6J28zjJxddScg2f8WWwKeepCi5AIEpSq+9hYC7VGsUOHhRBO83MzQD0sZa8E2rcvnCPwxQ0zv0Padh4I1J+7vs+yNw0oU2MsPSASgqMwElXw+IGeaU7EIILHHhgGMactENcBOWXfiZD0Ovk36oGexmzOB+vwx1POtdJpOFW9ZqRYKfRa3tq/3a0Bd06BtRgg48DM4Hg8Pm4I0Zea9wqMd4=
